### ISSUE TITLE
mirror-eslint not finding local .eslintrc file

### ISSUE THREAD

**Issue by janosh** [pre-commit/mirrors-eslint#32]
The pre-commit-installed version of eslint doesn't appear to find the local config file.

To reproduce, run `npm init svelte@next test-svelte-pre-commit` and select the app skeleton and reply yes to all other prompts. In the resulting project, `touch .pre-commit-config.yaml` and add

```yml
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
      - id: eslint
        files: \.(js|ts|svelte)$
        types: [file]
        args: [--fix]
        additional_dependencies:
          - eslint-plugin-svelte3
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
```

Now add any TS in a script tag for ESLint to find, e.g. append this to `src/routes/index.svelte`

```svelte
<script lang="ts">
	let foo: string;
</script>
```

Finally, run `pre-commit run eslint -av`

```sh
eslint...................................................................Failed
- hook id: eslint
- duration: 0.8s
- exit code: 1


test-svelte-pre-commit/src/routes/index.svelte
  2:9  error  Unexpected token  ParseError
```

whereas if I run the locally installed version of ESLint (after `npm i`) with `./node_modules/.bin/eslint src`, I get the expected output

```sh
test-svelte-pre-commit/src/routes/index.svelte
  2:6  warning  'foo' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (0 errors, 1 warning)
```

**Comment by asottile** [comment]
I get this:

```console
$ bash t.sh 
+ d=test-svelte-pre-commit
+ rm -rf test-svelte-pre-commit
+ npm init svelte@next test-svelte-pre-commit
npx: installed 5 in 0.9s

create-svelte version 2.0.0-next.77

Welcome to SvelteKit!

This is beta software; expect bugs and missing features.

If you encounter a problem, open an issue on https://github.com/sveltejs/kit/issues if none exists already.

✔ Which Svelte app template? › SvelteKit demo app
✔ Use TypeScript? … No / Yes
✔ Add ESLint for code linting? … No / Yes
✔ Add Prettier for code formatting? … No / Yes
✔ Copied project files

Want to add other parts to your code base? Visit https://github.com/svelte-add/svelte-adders, a community project of commands to add particular functionality to Svelte projects


Next steps:
  1: cd test-svelte-pre-commit
  2: npm install (or pnpm install, etc)
  3: git init && git add -A && git commit -m "Initial commit" (optional step)
  4: npm run dev -- --open

To close the dev server, hit Ctrl-C

Stuck? Visit us at https://svelte.dev/chat


+ cd test-svelte-pre-commit
+ cat
+ git init .
Initialized empty Git repository in /tmp/y/test-svelte-pre-commit/.git/
+ git add .

+ pre-commit run --all-files
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-eslint.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-eslint:@typescript-eslint/eslint-plugin,@typescript-eslint/parser,eslint-plugin-svelte3.
[INFO] Installing environment for https://github.com/pre-commit/mirrors-eslint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
eslint...................................................................Failed
- hook id: eslint
- exit code: 1

Executable `eslint` not found

```

I suspect you've missed the "adding plugins" part of the [README](https://github.com/pre-commit/mirrors-eslint#using-eslint-with-pre-commit)

**Comment by janosh** [comment]
Could you be more specific? Are you referring to `additional_dependencies`? You mean I was missing `eslint` itself as additional dep? I tried with and without that before posting here. Makes no difference for me.

```yml
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
      - id: eslint
        files: \.(js|ts|svelte)$
        types: [file]
        args: [--fix]
        additional_dependencies:
          - 'eslint@7.32.0' # does not help
          - '@typescript-eslint/eslint-plugin@4.29'
          - '@typescript-eslint/parser@4.29.0'
          - 'eslint-plugin-svelte3@3.2.0'
```

I'm surprised you're getting ``Executable `eslint` not found`` and I'm not. Maybe some global config is the problem here? I don't have a globally installed `eslint` at least:

```sh
zsh: command not found: eslint
```

**Comment by asottile** [comment]
now I get this:

```
$ pre-commit run --all-files
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-eslint:@typescript-eslint/eslint-plugin@4.29,@typescript-eslint/parser@4.29.0,eslint-plugin-svelte3@3.2.0,eslint@7.32.0.
[INFO] Installing environment for https://github.com/pre-commit/mirrors-eslint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
eslint...................................................................Failed
- hook id: eslint
- exit code: 2

Oops! Something went wrong! :(

ESLint: 7.32.0

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in /tmp/y/test-svelte-pre-commit/src and its ancestors. If it found none, it then looked in your home directory.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://eslint.org/chat/help


Oops! Something went wrong! :(

ESLint: 7.32.0

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in /tmp/y/test-svelte-pre-commit/src/routes/todos and its ancestors. If it found none, it then looked in your home directory.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://eslint.org/chat/help

```

please come up with a reproducible example otherwise I'm chasing ghosts :)

**Comment by asottile** [comment]
I found a random eslintrc that seems to "work" -- but your problem exists outside of pre-commit:

```console
$ npm i eslint@7.32.0 \
@typescript-eslint/eslint-plugin@4.29 \
@typescript-eslint/parser@4.29.0 \
eslint-plugin-svelte3@3.2.0
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN eslint-plugin-svelte3@3.2.0 requires a peer of svelte@^3.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN ~TODO~@0.0.1 No repository field.
npm WARN ~TODO~@0.0.1 No license field.

+ eslint-plugin-svelte3@3.2.0
+ eslint@7.32.0
+ @typescript-eslint/eslint-plugin@4.29.1
+ @typescript-eslint/parser@4.29.0
added 156 packages from 95 contributors and audited 156 packages in 8.776s

31 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities



asottile@asottile-VirtualBox:/tmp/y/test-svelte-pre-commit
$ ./node_modules/.bin/eslint $(git ls-files | grep svelte$)

Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Cannot find module 'svelte/compiler'
Require stack:
- /tmp/y/test-svelte-pre-commit/node_modules/eslint-plugin-svelte3/index.js
- /tmp/y/test-svelte-pre-commit/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /tmp/y/test-svelte-pre-commit/node_modules/@eslint/eslintrc/lib/index.js
- /tmp/y/test-svelte-pre-commit/node_modules/eslint/lib/cli-engine/cli-engine.js
- /tmp/y/test-svelte-pre-commit/node_modules/eslint/lib/eslint/eslint.js
- /tmp/y/test-svelte-pre-commit/node_modules/eslint/lib/eslint/index.js
- /tmp/y/test-svelte-pre-commit/node_modules/eslint/lib/cli.js
- /tmp/y/test-svelte-pre-commit/node_modules/eslint/bin/eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (/tmp/y/test-svelte-pre-commit/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at preprocess (/tmp/y/test-svelte-pre-commit/node_modules/eslint-plugin-svelte3/index.js:427:96)
    at Linter._verifyWithProcessor (/tmp/y/test-svelte-pre-commit/node_modules/eslint/lib/linter/linter.js:1304:30)
    at Linter._verifyWithConfigArray (/tmp/y/test-svelte-pre-commit/node_modules/eslint/lib/linter/linter.js:1273:25)
    at Linter.verify (/tmp/y/test-svelte-pre-commit/node_modules/eslint/lib/linter/linter.js:1235:25)
    at Linter.verify (/tmp/y/test-svelte-pre-commit/node_modules/eslint-plugin-svelte3/index.js:115:16)
    at Linter.verifyAndFix (/tmp/y/test-svelte-pre-commit/node_modules/eslint/lib/linter/linter.js:1428:29)
```

**Comment by janosh** [comment]
Thanks for the continued help with troubleshooting! I think I know now why you and me were getting different behavior. The problem seems to be related to other locally installed dependencies. If I do `rm -rf node_modules`, `pre-commit run -av` works correctly. If I do `npm install` and then try `pre-commit run -av` again, it get the `ParseError`. Could you try to confirm?

**Comment by asottile** [comment]
I'm pretty sure you're missing something in `additional_dependencies` -- my reproduction above does not involve `pre-commit` at all

**Comment by janosh** [comment]
I can't reproduce your "reproduction" and would like to find out why. If I do

```sh
npm i eslint@7.32.0 \
@typescript-eslint/eslint-plugin@4.29 \
@typescript-eslint/parser@4.29.0 \
eslint-plugin-svelte3@3.2.0
```

followed by

```sh
node_modules/.bin/eslint $(git ls-files | grep svelte$)
```

I get

```sh
test-eslint/src/routes/index.svelte
  2:6  warning  'foo' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (0 errors, 1 warning)
```

Can you post your random `.eslintrc`?

**Comment by asottile** [comment]
if you get that, I suspect you have a `./node_modules` existing before you ran anything -- I don't have the exact rc file but I just copied this one:

https://github.com/sveltejs/eslint-plugin-svelte3#installation

**Comment by janosh** [comment]
No, definitely no pre-existing `./node_modules`. I just came at this again from a clean slate and I still get different behavior from `eslint` vs `pre-commit` so I still suspect there's something wrong with this mirror.

Here's every step exactly how I did it:

```sh
npm init svelte@next pre-commit-svelte-eslint
# Which Svelte app template? › Skeleton project
# Use TypeScript? … Yes
# Add ESLint for code linting? … Yes
# Add Prettier for code formatting? … Yes

echo '\n<script lang="ts">let foo: string;</script>' >> src/routes/index.svelte

git init && git add -A && git commit -m "Initial commit"

rm -rf node_modules # shouldn't be there in the first place but just for good measure

npm i eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint-plugin-svelte3

node_modules/.bin/eslint $(git ls-files | grep svelte$)
```

This is the output:
 
```
pre-commit-svelte-eslint/src/routes/index.svelte
  2:6  warning  'foo' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (0 errors, 1 warning)
```

Everything as expected. If I then add this `.pre-commit-config.yaml`

```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
      - id: eslint
        files: \.(js|ts|svelte)$
        types: [file]
        args: [--fix]
        additional_dependencies:
          - eslint
          - svelte
          - typescript
          - eslint-plugin-svelte3
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
```

and run

```sh
pre-commit run --files src/routes/index.svelte
```

I get

```sh
eslint...................................................................Failed
- hook id: eslint
- exit code: 1


pre-commit-svelte-eslint/src/routes/index.svelte
  2:9  error  Unexpected token  ParseError

✖ 1 problem (1 error, 0 warnings)
```

**Comment by asottile** [comment]
you must have some prior (global?) installation that's being picked up is my only guess.  try it in a docker container to confirm the behaviour I posted above

**Comment by janosh** [comment]
Global installation of what? The ones I could think of (like `eslint` and `svelte`) I checked early on. Aren't globally installed. I think it's something more subtle. `eslint` when called by `pre-commit` does not use the ESLint Typescript plugin. The reason I think this is that by simply removing the single TypeScript syntax `let foo: string;` -> `let foo;` and rerun

```sh
pre-commit run --files src/routes/index.svelte
```

I instead get

```sh
eslint...................................................................Passed
```

**Comment by janosh** [comment]
Could it be that stuff installed as dev dependencies bleed into pre-commits environment?

That's one thing very specific to Svelte. Since it acts essentially like a compiler, all dependencies are only needed at compile-time and to be installed as dev deps. This is unlike other common JS frontend frameworks (React, Vue, Angular) which is perhaps why this issue would not have come up before.

In any case, the presence of `node_modules` should not interfere with `pre-commit`, right? I tried on several projects and the ESLint hook works fine after `rm -rf node_modules` but when I reinstall `npm i`, I get `Unexpected token  ParseError` on every Svelte file.

**Comment by janosh** [comment]
I think this error shows that the locally installed `eslint` shadows the one installed by the hook and that the problem is not some global install:

```sh
Failed
- hook id: eslint
- exit code: 2

Oops! Something went wrong! :(

ESLint: 8.6.0

ESLint couldn't determine the plugin "svelte3" uniquely.

- /Users/janosh/.cache/pre-commit/repo1h_h79co/node_env-system/lib/node_modules/eslint-plugin-svelte3/index.js (loaded in "CLIOptions")
- /Users/janosh/Repos/kit/site/node_modules/eslint-plugin-svelte3/index.js (loaded in "site/.eslintrc.yml")

Please remove the "plugins" setting from either config or remove either plugin installation.

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```

I triggered this error by adding

```diff
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.6.0
    hooks:
      - id: eslint
        types: [file]
        files: \.(svelte|js)$
+       args: [--plugin, eslint-plugin-svelte3]
        additional_dependencies:
          - eslint
          - svelte
          - typescript
          - eslint-plugin-svelte3
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
```

No matter where I specify a plugin for this hook (`eslintrc.yml` or `args`) it should in both cases try to load from it from `~/.cache/pre-commit`, no?
